<?php

return [
    'calendar' => 'Calendar',

    'calendar.create' => 'Add a calendar',
    'calendar.name' => 'Calendar name',
    'accounts' => 'Accounts',
    'calendars' => 'Calendars',
    'confirm' => 'Do you really want to delete this account?',
    'color' => 'Color',
    'accounts.stored' => 'Stored accounts',
    'create' => 'Create',
    'manage' => 'Manage calendars',
    'manage_accounts' => 'Manage accounts',
    'event.allday' => 'All day',
    'event.meeting' => 'Organize a meeting',
    'event.add' => 'Event',
    'event.save' => 'Save',
    'cancel' => 'Cancel',
    'my_tasks' => 'My tasks',
    'Tasks' => 'Tasks',
    'microsoft' => 'Microsoft Outlook',
    'google' => 'Google Calendar',
    'tasks' => 'Tasks',
    'module' => 'Module',
    '_field' => 'Field',
    'calendar.config' => 'Configurator for linking calendar events',
    'calendar.rules' => 'Set rules for automatically linking calendar events with CRM entities. The rules must be set in order of priority',
    'calendar.rule' => 'Rule',
    'save' => 'SAVE',
    'calendar.config.cron_delay' => 'Delay between two executions',
    'before_url' => 'Generated by ',
    'after_url' => 'End of generation',

    'empty' => [
        'account' => 'No accounts for the moment.',
        'calendar' => 'No calendar configured.',
    ],

    'field' => [
        'subject' => 'Subject',
        'start_date' => 'From',
        'end_date' => 'To',
        'category' => 'Category',
        'location' => 'Location',
        'description' => 'Description',
        'project' => 'Project',
        'calendar' => 'Calendar',
    ],

    'button' => [
        'add_account' => 'Add an account',
        'delete_account' => 'Delete this account',
    ],

    'period' => [
        'all' => 'All',
        'today' => 'Tody',
        'week' => 'Week',
        'month' => 'Month',
        'quarter' => 'Quarter',
    ],
];